# Generated by Django 2.0.5 on 2018-06-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='SourceFile',
        ),
        migrations.RenameField(
            model_name='error',
            old_name='File',
            new_name='source_file',
        ),
    ]
