# Generated by Django 2.0.5 on 2018-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_auto_20180604_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error',
            old_name='line',
            new_name='begin_line',
        ),
        migrations.AddField(
            model_name='error',
            name='end_line',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
